CREATE TABLE TINHTHANH (
    MaTinh VARCHAR2(6),
    TenTinh VARCHAR2(25),
    CONSTRAINT PK_TINHTHANH_MaTinh PRIMARY KEY (MaTinh)
);
CREATE TABLE TRAMTHUPHIBOT ( 
    MaTram VARCHAR2(6),
    TenTram VARCHAR2(25),
    DiaChi VARCHAR2(100),
    MaTinh VARCHAR2(6),
    TuyenDuong VARCHAR2(50),
    CONSTRAINT PK_TRAMTHUPHIBOT_Manv PRIMARY KEY (MaTram),
    CONSTRAINT FK_TRAMTHUPHIBOT_MaTinh FOREIGN KEY (MaTinh) REFERENCES TINHTHANH
);
CREATE TABLE KHACHHANG(
    MaKH VARCHAR2(6),
    HoKH VARCHAR2(20),
    TenKH VARCHAR2(25),
    NgaySinhKH DATE,
    GioiTinhKH VARCHAR2(25),
    DiaChiKH VARCHAR2(100),
    EmailKH VARCHAR2(25),
    SDTKH VARCHAR2(20),
    CCCDKH VARCHAR2(20),
    CONSTRAINT PK_KhachHang_MaKH PRIMARY KEY (MaKH),
    CONSTRAINT KhachHang_GioiTinh CHECK (GioiTinhKH IN ('Nam', N'Nữ')),
    CONSTRAINT KhachHang_Email UNIQUE (EmailKH),
    CONSTRAINT KhachHang_CCCDKH UNIQUE (CCCDKH)
);
CREATE TABLE XE ( 
        MaXe VARCHAR2(6),
        MaKH VARCHAR2(6),
        LoaiXe VARCHAR2(20),
        Mau VARCHAR2(20),
        BienSoXe VARCHAR2(20),
        CONSTRAINT PK_XE_MaXe PRIMARY KEY (MaXe),
        CONSTRAINT FK_XE_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG
    );
CREATE TABLE THETAG ( 
    MaVachThe VARCHAR2(6),
    MaXe VARCHAR2(6),
    MaKH VARCHAR2(6),
    SoDuTK NUMBER(12),
    CONSTRAINT PK_THETAG_MaVachThe PRIMARY KEY (MaVachThe),
    CONSTRAINT FK_THETAG_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG,
    CONSTRAINT FK_THETAG_MaXe FOREIGN KEY (MaXe) REFERENCES XE
);
CREATE TABLE VETHU ( 
    MaVeThu VARCHAR2(6),
    MaTram VARCHAR2(6),
    MaVachThe VARCHAR2(6),
    NgayGioThu DATE,
    CONSTRAINT PK_VETHU_MaVeThu PRIMARY KEY (MaVeThu),
    CONSTRAINT FK_VETHU_MaTram FOREIGN KEY (MaTram) REFERENCES TRAMTHUPHIBOT,
    CONSTRAINT FK_VETHU_MaVachThe FOREIGN KEY (MaVachThe) REFERENCES THETAG
);
CREATE TABLE TAIKHOAN (
  USERNAME VARCHAR2(50),
  PASSWORD VARCHAR2(50),
  QUYEN VARCHAR2(50),
  CONSTRAINT PK_TAIKHOAN PRIMARY KEY (USERNAME)
);

-----------------------Tạo bảng kiểm soát Hóa Đơn 
CREATE TABLE delete_history_KhachHang (
    DB_USER  VARCHAR2(128),
    TIMESTAMP DATE,
    STATEMENT_TYPE  VARCHAR2(7),
    SQL_TEXT  NVARCHAR2(2000)    
);
